name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  go_router: ^16.3.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.5.2

  # Data Modeling & Immutability
  freezed_annotation: ^2.4.4

  # Video Playback
  youtube_player_flutter: ^9.1.3

  # Firebase
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10

  # Local Database (ORM)
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Networking
  dio: ^5.4.0
  carousel_slider: ^5.1.1
  rxdart: ^0.28.0
  flutter_hooks: ^0.21.3+1
  video_player: ^2.10.0
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Build & Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
